-- =============================================================
-- LUNA ROSA — 01 · ESQUEMA DE LA BASE DE DATOS
-- Ejecutar en: Supabase Dashboard -> SQL Editor -> New query
--
-- Crea las tablas del menú, los horarios, la configuración y la
-- lista de administradores. Seguro de re-ejecutar: no borra ni
-- sobrescribe datos que ya existan.
--
-- Orden de ejecución: 01 -> 02 -> 03 -> 04
-- =============================================================


-- 1) CATEGORIAS ------------------------------------------------
-- El nombre incluye el emoji tal como se ve en la página
-- (por ejemplo "🍦 Conos & Canastas").
create table if not exists public.categorias (
  id      bigint generated by default as identity primary key,
  nombre  text    not null check (char_length(btrim(nombre)) between 1 and 60),
  orden   integer not null default 0
);


-- 2) PRODUCTOS -------------------------------------------------
create table if not exists public.productos (
  id             bigint generated by default as identity primary key,
  -- "restrict": la base se niega a borrar una categoría que aún tenga
  -- productos (la regla "solo si está vacía" queda garantizada aquí
  -- y no solo en el panel).
  categoria_id   bigint  not null references public.categorias(id) on delete restrict,
  nombre         text    not null check (char_length(btrim(nombre)) between 2 and 60),
  -- Pesos colombianos, entero y mayor que cero. Nunca decimales.
  precio         integer not null check (precio > 0),
  descripcion    text,
  -- Ruta relativa del repo ("Recursos/...") o URL absoluta de Storage.
  imagen_url     text,
  disponible     boolean not null default true,
  orden          integer not null default 0,
  -- Datos extra por producto (tamaños, sabores, toppings...). Hoy los
  -- productos no tienen ninguno, así que va en null; el panel no lo
  -- edita pero lo conserva intacto.
  opciones       jsonb,
  creado_en      timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists productos_categoria_idx on public.productos (categoria_id, orden);

-- actualizado_en se refresca solo en cada UPDATE
create or replace function public.set_actualizado_en()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.actualizado_en := now();
  return new;
end;
$$;

drop trigger if exists productos_set_actualizado_en on public.productos;
create trigger productos_set_actualizado_en
  before update on public.productos
  for each row execute function public.set_actualizado_en();


-- 3) HORARIOS --------------------------------------------------
-- dia_semana: 0 = domingo, 1 = lunes ... 6 = sábado (igual que
-- Date.getDay() en JavaScript).
-- Si cierra <= abre, se entiende que cierra pasada la medianoche.
create table if not exists public.horarios (
  dia_semana smallint primary key check (dia_semana between 0 and 6),
  abre       time    not null default '00:00',
  cierra     time    not null default '23:59',
  cerrado    boolean not null default false
);


-- 4) CONFIGURACION (una sola fila) ----------------------------
create table if not exists public.configuracion (
  id                    smallint primary key default 1 check (id = 1),
  -- false: la página no muestra horario dinámico ni bloquea pedidos.
  horario_activo        boolean not null default false,
  cerrado_temporalmente boolean not null default false,
  mensaje_cierre        text
);

insert into public.configuracion (id) values (1)
on conflict (id) do nothing;


-- 5) ADMINISTRADORES -------------------------------------------
-- Quién puede editar. Se llena a mano con 04-alta-admin.sql.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);


-- 6) es_admin() ------------------------------------------------
-- ¿El usuario con sesión iniciada está en admin_users?
-- SECURITY DEFINER para poder leer admin_users aunque el cliente no
-- tenga ningún acceso a esa tabla; search_path fijo por seguridad.
create or replace function public.es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;
